### PR TITLE
Update helm to 2.8.1

### PR DESCRIPTION
**Pull request by jhyelton**

### CODE REVIEW

**Comment by thomasbrezinski** [comment]
I know you said you setup the dockerhub triggers to support multiple versions, but are we deferring leveraging that (updating jenkins to allow specifying the version) until later?

**Review by markvdw4 — APPROVED** [review]
LGTM

**Comment by jhyelton** [comment]
Well, the upgrade has already been done so we still need to update the latest tag to point to the new version.  Are you suggesting the workflow should be updating the groovy code to reference the new image tag instead of updating the latest tag as well?  I thought the terraform var still defaults to the latest tag, it just supports being run with an alternate image tag.

**Comment by thomasbrezinski** [comment]
nah, I just meant that are we right now as part of this upgrade trying to keep the old version available in case we need to immediately add that flexibility and set the default to the old version

**Comment by jhyelton** [comment]
I did create a branch/image for helm 2.7.2 thats been built in docker hub, if we had to roll back in a hurry we could update the shared var to use that.

**Pull request merged**
