### PR TITLE
Update to 1.14.2 and remove deprecated tooling.

### PR DESCRIPTION
**Pull request by nadeem-syed**

### CODE REVIEW

**Comment by bdurette** [comment]
I think this is directionally correct, however, I think when we created the 1.14.2 branch, we identified that there were other production containers that were based on master. Seems like this could break those repos.

**Comment by dbrian** [comment]
Yeah, we should make a best effort at notifying offenders... but in the end I think it's ok if some builds fail for not pinning a version.

**Comment by nadeem-syed** [comment]
what is the best way to identify who is using this in production?

**Comment by anneal** [comment]
At one point, we attempted to add a changelog and versioning to the Golang base image. 

https://github.com/wpengine/base-images-public/tree/master/golang#changelog
https://github.com/wpengine/base-images-public/tree/master/golang#versions

Based on that, releasing new image [tags](https://hub.docker.com/r/wpengine/golang/tags) of `latest`, `1.14`, and `1.14-wpe0` sounds like the approach documented here. Does that match others' expectations? 

For finding other repos using this in production, these searched could be helpful. I imagine a general heads up is sufficient for teams to check for themselves though.
https://github.com/search?q=org%3Awpengine+%22wpengine%2Fgolang%3Alatest%22&type=Code
https://github.com/search?p=1&q=org%3Awpengine+%22wpengine%2Fgolang%22&type=Code

**Comment by courtney-curtis** [comment]
Awesome to see this! @limbalrings and I were just talking about wanting to update this last week.

Looking at this - https://hub.docker.com/r/wpengine/golang/tags - I don't see a 1.13. Does that mean version 1.13 can't be specified for the wpe golang image? The backups service is using this image, and therefore 1.12, so our plan was to move to 1.13 as a first step.

**Review by will0 — APPROVED** [review]
Sounds like as long as we're generous with notifications this is the correct forward change.

**Comment by courtney-curtis** [comment]
Install backup service is good to go with this change!

**Pull request merged**
